import { celo, celoSepolia } from "wagmi/chains";

export type Token = {
  symbol: string;
  name: string;
  /** Single character displayed in the circular badge */
  char: string;
  /** Badge background color */
  color: string;
  /** Badge foreground/text color */
  fg: string;
  /** URL to token logo image (PNG) */
  logoUrl: string;
  decimals: number;
  /** Decimal places to show in the UI */
  displayDecimals: number;
  /** True = native gas token (use useBalance). No entry in addresses needed. */
  isNative: boolean;
  /**
   * ERC-20 contract address per chain ID.
   * Missing key = token not deployed on that chain.
   *
   * Source: https://docs.celo.org (Token Contracts page, autogenerated)
   */
  addresses: Partial<Record<number, `0x${string}`>>;
};

export const TOKENS: Token[] = [
  {
    symbol: "CELO",
    name: "Celo",
    char: "C",
    color: "#FBCC5C",
    fg: "#3D3200",
    logoUrl:
      "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/celo/info/logo.png",
    decimals: 18,
    displayDecimals: 4,
    isNative: true,
    addresses: {},
  },
  {
    // USDm is the Mento Dollar (formerly cUSD). Same contract address.
    symbol: "USDm",
    name: "Mento Dollar",
    char: "m",
    color: "#35D07F",
    fg: "#fff",
    logoUrl:
      "https://coin-images.coingecko.com/coins/images/13161/large/icon-celo-dollar-color-1000-circle-cropped.png",
    decimals: 18,
    displayDecimals: 2,
    isNative: false,
    addresses: {
      [celo.id]: "0x765DE816845861e75A25fCA122bb6898B8B1282a",
      [celoSepolia.id]: "0xEF4d55D6dE8e8d73232827Cd1e9b2F2dBb45bC80",
    },
  },
  {
    symbol: "USDC",
    name: "USD Coin",
    char: "U",
    color: "#2775CA",
    fg: "#fff",
    logoUrl:
      "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/celo/assets/0xcebA9300f2b948710d2653dD7B07f33A8B32118C/logo.png",
    decimals: 6,
    displayDecimals: 2,
    isNative: false,
    addresses: {
      [celo.id]: "0xcebA9300f2b948710d2653dD7B07f33A8B32118C",
      [celoSepolia.id]: "0x01C5C0122039549AD1493B8220cABEdD739BC44E",
    },
  },
  {
    symbol: "USDT",
    name: "Tether USD",
    char: "T",
    color: "#26A17B",
    fg: "#fff",
    logoUrl:
      "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/celo/assets/0x48065fbBE25f71C9282ddf5e1cD6D6A887483D5e/logo.png",
    decimals: 6,
    displayDecimals: 2,
    isNative: false,
    addresses: {
      [celo.id]: "0x48065fbBE25f71C9282ddf5e1cD6D6A887483D5e",
      [celoSepolia.id]: "0xd077A400968890Eacc75cdc901F0356c943e4fDb",
    },
  },
];

export const NATIVE_TOKEN = TOKENS.find((t) => t.isNative)!;
export const ERC20_TOKENS = TOKENS.filter((t) => !t.isNative);
